<a href="https://colab.research.google.com/github/tze-suen/data-science-toolkit/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# 1. create a numpy array of size 2*2
import numpy as np
arr_2x2 = np.array([[1,2],[3,4]])
print(arr_2x2)

[[1 2]
 [3 4]]


In [29]:
# 2. create a random numpy array of size 3*4
arr_random_3x4 = np.random.rand(3,4)
print(arr_random_3x4)

[[0.51479001 0.90387342 0.59902065 0.64470029]
 [0.72174165 0.4074943  0.05660231 0.18498658]
 [0.46371984 0.00553584 0.35724158 0.05751238]]


In [30]:
# 3. create a numpy array of ones and a numpy array of zeroes
arr_ones = np.ones((2,3))
arr_zeroes = np.zeros((2,3))
print(arr_ones)
print(arr_zeroes)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# 4. create a random numpy array of size 6*3 and transpose it
arr_6x3 = np.random.rand(6,3)
arr_transposed = arr_6x3.T
print(arr_transposed)

[[0.74122455 0.98892089 0.05536829 0.29441969 0.21374872 0.81007489]
 [0.94003863 0.98399241 0.48375052 0.97703602 0.42298377 0.51592955]
 [0.98976844 0.23993533 0.50114068 0.61732526 0.628713   0.80196035]]


In [37]:
# 5. create two random numpy array of size n*p and p*m and then compute the dot product
import numpy as np

n=4
p=2
m=5

arr_nxp = np.random.rand(n,p)
arr_pxm = np.random.rand(p,m)
dot_product = np.dot(arr_nxp,arr_pxm)

print(arr_nxp)
print(arr_pxm)
print(dot_product)

[[0.26710865 0.95878738]
 [0.26522356 0.31223694]
 [0.94112255 0.87284569]
 [0.34950552 0.77813386]]
[[0.96771528 0.23210181 0.90344348 0.71487236 0.17047276]
 [0.65340276 0.96906634 0.72721505 0.15345753 0.9345138 ]]
[[0.88495945 0.99112498 0.93856219 0.33808173 0.94153479]
 [0.46067738 0.36413718 0.4666779  0.2375161  0.33700312]
 [1.48105846 1.06428163 1.48499756 0.80672724 0.9761221 ]
 [0.84665664 0.8351842  0.88162914 0.36926233 0.786758  ]]
